---
steps:
  - label: ':brush: Pretending I am linting'
    key: lint
    command: |
      exit 1
    soft_fail:
      - exit_status: '*'
  - label: ':eye: Check linting results'
    depends_on: lint
    command: |-
      if [ $$(buildkite-agent step get "outcome" --step "lint") == "passed" ]; then
        echo "LMAO! GOTEM!"
      else
        cat << YAML | buildkite-agent pipeline upload
          steps:
            - block: ":sus: Review lint failures"
              prompt: "Don't let them win."
      YAML
      fi
