---
steps:
  - label: ':zsh: Run a command and save its success status'
    key: lint
    command: |
      ls -la
    soft_fail:
      - exit_status: '*'
  - wait
  - label: ':confetti: OR :poop:?'
    command: |
      echo "I ran because the previous command succeeded."
    if: build.state('lint') == 'passed'
