---
steps:
  - label: ':zsh: Pretending I am linting'
    key: lint
    command: |
      exit 1
    soft_fail:
      - exit_status: '*'
  - label: ':fire: Check linting results'
    trigger: linting-the-lint
    if: $$(buildkite-agent step get "outcome" --step "lint") == "passed"
