---
steps:
  - label: ':x: I am not really linting'
    key: lint-not
    command: |
      exit 1
    soft_fail:
      - exit_status: '*'
  - label: ':eye: Check linting results'
    depends_on: lint-not
    command: |-
      if [ $$(buildkite-agent step get "outcome" --step "lint-not") == "passed" ]; then
        echo "LMAO! GOTEM!"
      else
        cat << YAML | buildkite-agent pipeline upload
          steps:
            - block: ":spy: Review lint failures"
              prompt: "Don't let them win."
      YAML
      fi
  - label: ':check: I am really linting'
    key: lint
    command: |
      exit 0
    soft_fail:
      - exit_status: '*'
  - label: ':eye: Check linting results'
    depends_on: lint
    command: |-
      if [ $$(buildkite-agent step get "outcome" --step "lint") == "passed" ]; then
      echo ":troll: LMAO! GOTEM!"
      else
        cat << YAML | buildkite-agent pipeline upload
          steps:
            - block: ":sus: Review lint failures"
              prompt: "Don't let them win."
      YAML
      fi
