---
steps:
  - label: ':zsh: Pretending I am linting'
    key: lint
    command: |
      exit 1
    soft_fail:
      - exit_status: '*'
  - label: ':fire: Check linting results'
    depends_on: lint
    command: |-
      if [ $$(buildkite-agent step get "outcome" --step "lint") == "passed" ]; then
        echo "We fooled them!"
      else
        echo "They didn't fall for it"
      fi
